FROM docker-registry.guokr.com/guokr/gandalf-env

ADD . /bower
WORKDIR /bower

RUN npm install --registry https://registry.npm.taobao.org -g gulp-cli \
    && PHANTOMJS_CDNURL=https://npm.taobao.org/mirrors/phantomjs npm install --registry https://registry.npm.taobao.org \
    && bower install --allow-root --config.interactive=false
